apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beepbeep
  namespace: intersection
  labels:
    name: beepbeep
spec:
  selector:
    matchLabels:
      name: beepbeep
  template:
    metadata:
      labels:
        name: beepbeep
    spec:
      containers:
      - name: beepbeep
        image: denhamparry/app-3de9011a2d7a88b77bd0cff16b71b356
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      terminationGracePeriodSeconds: 30
