

name: Container Build workflows
on:
  push:
  workflow_dispatch:

# permission can be added at job level or workflows level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  ContainerBuild:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.2'

      - run: go version

      - name: Install Crane
        run: go install github.com/google/go-containerregistry/cmd/crane@latest

      - run: crane version

      - name: Install Cosign
        uses: sigstore/cosign-installer@v2.8.0
        with:
          cosign-release: 'v1.13.1'

      - name: Check install - cosign!
        run: cosign version

      - name: Docker login
        shell: bash
        run: |
          export AWS_ECR_LOGIN=$(aws ecr get-login-password --region ${AWS_REGION})
          cosign login -u AWS -p ${AWS_ECR_LOGIN} ${AWS_ECR_LOGIN_URL}
          crane auth login ${AWS_ECR_LOGIN_URL} -u AWS -p ${AWS_ECR_LOGIN}